# Generated by Django 4.1 on 2023-06-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_alter_tenant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
