# Generated by Django 4.1 on 2023-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_delete_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
