# Generated by Django 4.1 on 2023-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_apartment_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Itahari', 'Itahari'), ('Butwal', 'Butwal'), ('Birtamode', 'Birtamode')], max_length=100),
        ),
    ]
