# Generated by Django 4.1 on 2023-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_alter_apartment_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_available',
        ),
        migrations.AddField(
            model_name='apartment',
            name='bhk',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Forth', 'Forth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('Nineth', 'Nineth'), ('Tenth', 'Tenth')], default='Ground', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
