# Generated by Django 4.1 on 2023-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_alter_apartment_bhk_alter_apartment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ac',
            field=models.BooleanField(default=False),
        ),
    ]
