# Generated by Django 4.1 on 2023-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0015_alter_apartment_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('bhk', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('parking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
            ],
        ),
    ]
