# Generated by Django 4.1 on 2023-07-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0016_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
