# Generated by Django 4.1 on 2023-08-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_alter_apartment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Itahari', 'Itahari'), ('Butwal', 'Butwal'), ('Gaushala', 'Gaushala'), ('Baneshwor', 'Baneshwor'), ('Maharajgunj', 'Maharajgunj')], max_length=100),
        ),
    ]
