# Generated by Django 4.1 on 2023-06-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_apartment_delete_tenant'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='apartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.apartment'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='apartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.apartment'),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
