# Generated by Django 4.1 on 2023-05-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_apartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
