# Generated by Django 4.1 on 2023-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
