# Generated by Django 4.1 on 2023-07-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
